FROM maven:3.9.4-eclipse-temurin-21 AS build

WORKDIR /Skedula

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jdk AS runtime

WORKDIR /Skedula


COPY --from=build /Skedula/target/Skedula-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
