spring.application.name=Skedula

#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/skedula}
spring.datasource.url=jdbc:postgresql://localhost:5432/skedula
#spring.datasource.username=${DB_NAME:postgres}
spring.datasource.username=postgres
#spring.datasource.password=${DB_PASSWORD:0000}
spring.datasource.password=0000
spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=gfeFGevfegurafgE8egfu3gef7ug3efgVBCbw28G2g8E38ugf7rg123830efebvnNCNCHihhqiewehrh83h84791049148urhbdvvfgEUHFoeh 

spring.web.resources.static-locations=classpath:/static/

spring.mail.username=${MAIL_SERVICE_EMAIL:skedula.service@gmail.com}
spring.mail.password=${MAIL_SERVICE_PASSWORD:dummypassword}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

uploadcare.publicKey=${UPLOADCARE_PUBLIC_KEY:540496cdc68e452d5843}
uploadcare.secretKey=${UPLOADCARE_SECRET_KEY:24ce490fb698da7b7188}

razorpay.keyId=${RAZORPAY_KEY_ID:rzp_test_1osnPBeF2xSAFe}
razorpay.secret.key=${RAZORPAY_KEY_SECRET:j56sb6intnUIua5oyE5mKvwe}
